GET http://localhost:3000/
####
POST http://localhost:3000/new-round
####
POST http://localhost:3000/close
####
POST http://localhost:3000/store-results
Content-Type: application/json
//Accept-Language: en-US,en;q=0.5

{
    "numbers": [2, 3, 4, 5, 6, 7, 8, 9]
}

####

POST http://localhost:3000/close
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImdXZXhMT3cxY3hDQl9NNEpsQjMyNiJ9.eyJpc3MiOiJodHRwczovL2Rldi01anpuOGY2NTdsamkzb3RkLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJxT2ZYNk5leTRzTU9PdjJjRXFXV3hRUGZZRE5yV3RtSUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9sb3R0by9hcGkiLCJpYXQiOjE3NjEzMjE4NzAsImV4cCI6MTc2MTQwODI3MCwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIiwiYXpwIjoicU9mWDZOZXk0c01PT3YyY0VxV1d4UVBmWUROcld0bUkifQ.i2IndhRq71XIN1XSdsUVNMyBc5vxJrw_aLA5_MdbUegKgcTqyDsFk1mljzQ0UEgadx747btAo46suNbnkPdBDunDsPu4efMegQ0TeJ-nLyqcp3mDiteLJgNNrjlRg8l1aaRz0fKNyEiVS1Yi9gaY1hNvZ2xmVHVW56MlTp0XvRTUomZPD5vvQrv2irTa6moHHcC6KXeuF5muYZ8j4cvz1iyvb0vbjt5L6JOl1g2nluw_6VilxrbI-sCZ32aSYAFia9uG8ULo9B-mUhdTp0cDWlMUcXs1CsbTOTbtqZZBSrUIFFUOQkr975pp9dshvpfBZ2kr-RsYz1IDK-_R6A1fSw
####
POST http://localhost:3000/new-round
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImdXZXhMT3cxY3hDQl9NNEpsQjMyNiJ9.eyJpc3MiOiJodHRwczovL2Rldi01anpuOGY2NTdsamkzb3RkLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJxT2ZYNk5leTRzTU9PdjJjRXFXV3hRUGZZRE5yV3RtSUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9sb3R0by9hcGkiLCJpYXQiOjE3NjEzMjE4NzAsImV4cCI6MTc2MTQwODI3MCwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIiwiYXpwIjoicU9mWDZOZXk0c01PT3YyY0VxV1d4UVBmWUROcld0bUkifQ.i2IndhRq71XIN1XSdsUVNMyBc5vxJrw_aLA5_MdbUegKgcTqyDsFk1mljzQ0UEgadx747btAo46suNbnkPdBDunDsPu4efMegQ0TeJ-nLyqcp3mDiteLJgNNrjlRg8l1aaRz0fKNyEiVS1Yi9gaY1hNvZ2xmVHVW56MlTp0XvRTUomZPD5vvQrv2irTa6moHHcC6KXeuF5muYZ8j4cvz1iyvb0vbjt5L6JOl1g2nluw_6VilxrbI-sCZ32aSYAFia9uG8ULo9B-mUhdTp0cDWlMUcXs1CsbTOTbtqZZBSrUIFFUOQkr975pp9dshvpfBZ2kr-RsYz1IDK-_R6A1fSw
####